name: kursova
description: "Облік витрат"
publish_to: 'none'


version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/dollar_icon.png"
  min_sdk_android: 23
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/dollar_icon.png"

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/dollar_icon.png
  uses-material-design: true

